- name: Configure new servers 
  hosts: all
  become: true
  tasks:
    - name: install used package
      yum: pkg={{item}} update_cache=yes cache_valid_time=3600
      with_items:
        - mc
        - git
        - vim
        - htop
        

    - name: copy vimrc file configuration
      copy: src=files/.vimrc dest=~
      
    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644
        
    - name: restart nginx
      service: name=nginx state=restarted
